### ISSUE TITLE
Templates refers to gitlab

### ISSUE THREAD

**Issue by npalm** [philips-labs/.github#1]
## Summary

@ThomasHagebols thanks for adding the templates, seems at least the bug report refers to GitLab.

## Steps to reproduce

Create bug report

## What is the expected *correct* behavior?

Check tempales for old / gitlab references

## Relevant logs and/or screenshots

n/a

## Other links/references

https://raw.githubusercontent.com/philips-labs/.github/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ThomasHagebols** [comment]
Resolved
